### PR TITLE
Solarfactors notebook

### PR DESCRIPTION
**Pull request by echedey-ls**
See #8

### CODE REVIEW

**Comment by echedey-ls** [comment]
Let me know what you think @kandersolar, and if I've missed doing something.

**Comment by kandersolar** [comment]
Thanks @echedey-ls!  The figure below doesn't look great by default, but I think it's okay since the figure is interactive (zoom, hover, etc).  

image

Is there anything else you want to do before merging?  It is fine with me as-is.

**Comment by echedey-ls** [comment]
Honestly, I wasn't able to make sphinx build the webpage, only the notebook. But if you can make it work, that's fine then.

> Is there anything else you want to do before merging? It is fine with me as-is.

Nothing else from my side, no.

**Comment by kandersolar** [comment]
Thanks @echedey-ls!

**Pull request merged**
